from enum import Enum

PLAYER_COUNT = 4
INITIAL_TROOPS = 2
INITIAL_AGENTS = 2
MAX_ROUNDS = 9
MAX_SPICE_SILO = 3
ACTION_TYPES = 3

HIRE_MERCENARIES_TROOPS_PRODUCED = 2
HIRE_MERCENARIES_DEPLOYMENT_LIMIT = 3

QUICK_STRIKE_TROOPS_PRODUCED = 1
QUICK_STRIKE_DEPLOYMENT_LIMIT = 2

TROOP_TRANSPORTS_TROOPS_PRODUCED = 0
TROOP_TRANSPORTS_DEPLOYMENT_LIMIT = 4

MOBILIZATION_TROOPS_PRODUCED = 0
MOBILIZATION_DEPLOYMENT_LIMIT = 5

class ActionType(Enum):
	ECONOMIC = 1
	MILITARY = 2
	POLITICAL = 3

class Action(Enum):
	# Economic actions
	CONSTRUCT_PALACE = 1
	HARVESTER = 2
	REFINERY = 3
	SPICE_SILO = 4
	SELL_MELANGE = 5
	SECURE_CONTRACT = 6
	# Military actions
	HOLTZMAN_SHIELD = 7
	STONE_BURNER = 8
	HIRE_MERCENARIES = 9
	QUICK_STRIKE = 10
	RECRUITMENT_CENTER = 11
	TROOP_TRANSPORTS = 12
	LOOT_VILLAGES = 13
	# Political actions
	SWORDMASTER = 14
	SARDAUKAR = 15
	AUDIENCE_WITH_EMPEROR = 16
	MOBILIZATION = 17
	SEEK_ALLIES = 18
	POLITICAL_MANEUVERING = 19

class Cost:
	CONSTRUCT_PALACE = 6
	SWORDMASTER = 6
	SELL_MELANGE = 3
	HOLTZMAN_SHIELD = 3
	STONE_BURNER = 2
	HIRE_MERCENARIES = 2
	SARDAUKAR = 3
	AUDIENCE_WITH_EMPEROR = 3
	MOBILIZATION = 2
	SEEK_ALLIES = 1