from enum import Enum

PLAYER_COUNT = 4
INITIAL_TROOPS = 2
INITIAL_AGENTS = 2
MAX_ROUNDS = 8
MAX_SPICE_SILO = 3

class ActionType(Enum):
	ECONOMIC = 1
	MILITARY = 2
	POLITICAL = 3

class Action(Enum):
	# Economic actions
	CONSTRUCT_PALACE = 1
	HARVESTER = 2
	REFINERY = 3
	SPICE_SILO = 4
	SELL_MELANGE = 5
	SECURE_CONTRACT = 6
	# Military actions
	STONE_BURNER = 7
	HIRE_MERCENARIES = 8
	QUICK_STRIKE = 9
	RECRUITMENT_CENTER = 10
	TROOP_TRANSPORTS = 11
	LOOT_VILLAGES = 12
	# Political actions
	SWORDMASTER = 13
	SARDAUKAR = 14
	AUDIENCE_WITH_EMPEROR = 15
	MOBILIZATION = 16
	SEEK_ALLIES = 17
	POLITICAL_MANEUVERING = 18

class Cost:
	CONSTRUCT_PALACE = 6
	SWORDMASTER = 8
	SELL_MELANGE = 3
	STONE_BURNER = 4
	HIRE_MERCENARIES = 2
	SARDAUKAR = 4
	AUDIENCE_WITH_EMPEROR = 3
	MOBILIZATION = 2